
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.customerservice;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-08T19:42:13.181+05:30
 * Generated source version: 3.2.2
 *
 */

@javax.jws.WebService(
                      serviceName = "CustomerServiceService",
                      portName = "CustomerServicePort",
                      targetNamespace = "http://customerservice.example.com/",
                      wsdlLocation = "CustomerService.wsdl",
                      endpointInterface = "com.example.customerservice.CustomerService")

public class CustomerServicePortImpl implements CustomerService {

    private static final Logger LOG = Logger.getLogger(CustomerServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.example.customerservice.CustomerService#updateCustomer(com.example.customerservice.Customer customer)*
     */
    public void updateCustomer(com.example.customerservice.Customer customer) {
        LOG.info("Executing operation updateCustomer");
        System.out.println(customer);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.example.customerservice.CustomerService#getCustomersByName(java.lang.String name)*
     */
    public java.util.List<com.example.customerservice.Customer> getCustomersByName(java.lang.String name) throws NoSuchCustomerException   {
        LOG.info("Executing operation getCustomersByName");
        System.out.println(name);
        try {
            java.util.List<com.example.customerservice.Customer> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NoSuchCustomerException("NoSuchCustomerException...");
    }

}
