/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pkumar' at '26/9/17 5:24 PM' with Gradle 2.4
 *
 * @author pkumar, @date 26/9/17 5:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
