/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pkumar' at '15/6/17 2:50 PM' with Gradle 2.4
 *
 * @author pkumar, @date 15/6/17 2:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
